OUT = ../mkrfs ../rfs_add ../rfs_df ../rfs_ls ../rfs_tree ../rfs_extract ../rfs_chmod ../rfs_mkdir ../rfs_fsck ../rfs_info ../rfs_ln ../rfs_boot ../rfs_rm ../rfs_chown ../rfs_chgrp ../rfs_mknod
OUT_FUSE = ../rfs_mount

include ../../config.mk
include ../../tools.mk